### PR TITLE
Add python3 support

### PR DESCRIPTION
**Pull request by souravsingh**

### CODE REVIEW

**Comment by jingchunzhu** [comment]
@souravsingh will python3 version work with python 2 as well, or only with python 3?

**Comment by souravsingh** [comment]
I should work nicely. I am not able to test the build since the repo does not contain ``setup.py`` from which I can build.( Correction, I found it)

**Comment by souravsingh** [comment]
@jingchunzhu There is a small problem with compatibility in ``xenaQuery.py``, otherwise rest of the scripts work really nicely in python2

**Comment by jingchunzhu** [comment]
@souravsingh  so you mean it will not work with python2? We need the code work with python 2, if it is also work with python 3, it is better.

**Comment by souravsingh** [comment]
It will work with both. I just need to make a small modification in ``xenaQuery.py`` regarding ``urllib`` import to ensure that it works for both Python 2 and 3.

**Comment by jingchunzhu** [comment]
that will be great.

**Comment by souravsingh** [comment]
@jingchunzhu I have made the changes and have tested the repo locally. Would you kindly test the PR before pushing the code?

**Pull request merged**
